### ISSUE TITLE
# Database Schema:

### ISSUE THREAD

**Issue by Evan-Leon** [jhkl12/AllJourneys#2]
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
- [x] foreign key and table name are lowercased, snake_cased and back_ticked
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table’s name are lowercased, snake_cased and back_ticked
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and back_ticked

**Comment by Evan-Leon** [comment]
Awesome job on the schema! A few notes:

- please make sure all tables names are back-ticked  `` 
- Also you will probably need to add lng and lat to your trails table and maybe parks table (look at benches from benchBnB for guidance on how to put them into the table)

**Comment by zkural1** [comment]
Good idea! Thanks Evan. I've updated the table names with back-ticks and added 'lng' and 'lat' rows to  the trails and parks tables .
