### ISSUE TITLE
# Sample State:

### ISSUE THREAD

**Issue by Evan-Leon** [jhkl12/AllJourneys#5]
- [x] State shape is flat!
- [x] State’s keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ```javascript...```). This will display the state as a code block instead of a giant line of text
    - [x] Top level slices
        - [x] entities
        - [x] session
        - [x] errors (here or in ui)
        - [x] ui (if needed)
    - [x] Should NOT have nested slices, aka comments inside of posts
        - Some info from other tables is ok, for instance:
            - the author username and imageurl for a post. basically any info that the user can’t change
            - like count and a boolean on whether the user likes the post instead of a likes slice

**Comment by Evan-Leon** [comment]
Great job on sample state! Only question I have is will you be using modals? If so please add a modal to the ui slice of state, if not you are all set :)

**Comment by zkural1** [comment]
Thanks Evan. Alltrails doesn't have any modals so looks like this part is all set
