### ISSUE TITLE
# Parks Feature

### ISSUE THREAD

**Issue by Evan-Leon** [jhkl12/AllJourneys#9]
## Functionality
 - [ ] Delivered promised functionality
 - [ ] Smooth, bug free navigation

## Style
 - [ ] The elements are positioned correctly on the page
 - [ ] Full styling

## Crud (*only those that apply)
 - [ ] Create
 - [ ] Read
 - [ ] Update
 - [ ] Destroy

## Seeds
 - [ ] Adequate and appropriate seeds

 ## Additional
 - [ ] No dead links
 - [ ] No unecessary buttons or text
 - [ ] Works fully on Heroku

**Comment by zkural1** [comment]
Just need to update filters when clicked. Which will be done once trails are set up

**Comment by Evan-Leon** [comment]
- I don't seem to be able to make it to a park page, even when typing '/parks/1' into the url
- how should I got about finding the parks?

**Comment by zkural1** [comment]
Sorry about that Evan, I had to reseed the database on heroku and I should've specified the link for the park. You can follow the below link. Users will be able to find the park once the search feature is working

https://alljourneys.herokuapp.com/#/parks/1
